[volume.root]
type = btrfs
location = /mnt/btrfs_root/@
snapshot_destination = /snapshots
retention = "24h 7d 4w 12m"

[volume.data]
type = zfs
location = datapool/data
retention = "24h 7d 4w 12m"

[volume.home]
type = zfs
location = datapool/home
retention = "48h 14d 8w 12m"
